export const images = {
    logo: require("./assets/logo.png"),
    logo_white: require("./assets/white.png"),
    logo_black: require("./assets/black.png"),
    cover: require("./assets/cover.jpg"),
    profil: require("./assets/profil.jpg"),
    avatar: require("./assets/avatar.png"),
    post: require("./assets/7.jpg"),

    img1: require("./assets/1.png"),
    img2: require("./assets/2.jpg"),
    img3: require("./assets/3.png"),
    img4: require("./assets/4.png"),
    img5: require("./assets/5.png"),
    img6: require("./assets/7.jpg"),

    //categoires
    background: require("./assets/categories/bijou.jpg"),
    vehicule: require("./assets/categories/vehicule.jpeg"),
    immobilier: require("./assets/categories/immobilier.jpg"),
    electronique: require("./assets/categories/electronique.jpg"),
    loisir: require("./assets/categories/livre.jpg"),
    bijou: require("./assets/categories/bijou.jpg"),
    vetement: require("./assets/categories/vetement.jpg"),
    jeux: require("./assets/categories/jeux.jpg"),
    sport: require("./assets/categories/sport.jpg"),
    cosmetique: require("./assets/categories/cosmetique.jpg"),
    electromenager: require("./assets/categories/electromenager.jpg"),
    medical: require("./assets/categories/medical.jpg"),
    alimentaire: require("./assets/categories/alimentaire.jpg"),
    animal: require("./assets/categories/animal.jpg"),
    livre: require("./assets/categories/livre.jpg"),
    antiquite: require("./assets/categories/antiquite.jpg"),
    scientifique: require("./assets/categories/scientifique.jpg"),
    jardinage: require("./assets/categories/jardinage.jpg"),
}